### ISSUE TITLE
Poise-python switch breaks master suite

### ISSUE THREAD

**Issue by rettigs** [osuosl-cookbooks/osl-jenkins#21]
c3144a3021129c8de7530e86a8342fe4f4764cf2 breaks the master suite/recipe, preventing it from even converging.  This is making it difficult to test PRs since the master branch won't even converge.  For now, I'll rebase my PRs off of an older commit, but this still needs to be fixed.

@armiller Please advise.

**Comment by armiller** [comment]
How exactly does it break?

**Comment by armiller** [comment]
The only problem I had was pinning the iptables version in the Berksfile to '< 2.2.0' since it newer version require chef 12.5. Other than that it converged just fine.

**Comment by rettigs** [comment]
Perhaps my Berksfile.lock was out of date.  I'll try again.

**Comment by rettigs** [comment]
Yep, my Berksfile.lock was out of date.  My apologies for not providing enough information in the original report.
