### ISSUE TITLE
Cookbook uploader doesn't upload correctly

### ISSUE THREAD

**Issue by fahlmant** [osuosl-cookbooks/osl-jenkins#36]
Not sure if this is the right place to put this issue, but the uploader bumps the cookbook but it does not get get uploaded to the chef server

**Comment by ramereth** [comment]
@armiller is this the issue where you mentioned we should switch this to ``knife cookbook upload`` instead?

**Comment by armiller** [comment]
Yep `knife cookbook upload $foo --freeze`
